Feature/feature tip
scm-manager/scm-landingpage-plugin pull request #46
Opened 2021-11-26 12:38 UTC by Pilopa

## Proposed changes

Adds a new tile that shows a random feature tip with a link to the documentation on the scm-manager website.

### Your checklist for this pull request

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

**Contributor**:
- [ ] PR is well described and the description can be used as a commit message on squash
- [ ] Related issues linked to PR if existing and labels set
- [ ] New code is covered with unit tests
- [ ] New ui components are tested inside the storybook (module ui-components only) 
- [ ] [Changelog entry file](https://github.com/scm-manager/changelog#changelog-entry-files) created in `gradle/changelog` or CHANGELOG.md is updated for plugins
- [ ] Feature has been tested with different permissions
- [ ] Documentation updated (only necessary for new features or changed behaviour)

**Reviewer**:
- [ ] The clean code principles are respected ([CleanCode](https://clean-code-developer.com/virtues/))
- [ ] All new code/logic is implemented on the right spot / "Should this be done here?"
- [ ] UI changes fits into the layout
- [ ] The UI views / components are responsive (mobile views)
- [ ] Correct translations are available

### Checklist for branch merge request (not required for forks)

- [ ] Branch is green/blue on [Jenkins](https://oss.cloudogu.com/jenkins/)
- [ ] Quality Gate passed on [SonarQube](https://sonarcloud.io/organizations/scm-manager/projects)

2021-11-26 13:13 UTC, Pilopa commented
Requires https://github.com/scm-manager/scm-manager/pull/1875

2021-11-29 10:10 UTC, eheimbuch commented
Does not work

![Screenshot from 2021-11-29 11-09-46](https://user-images.githubusercontent.com/50202942/143848615-e80dcb3f-f167-4658-8673-7018cfe2ace4.png)

2021-11-29 10:33 UTC, eheimbuch requested changes

2021-11-29 10:33 UTC, eheimbuch commented on src/main/js/tips/MyTips.tsx
> +  );
Move hook to own file?

2021-11-29 17:52 UTC, Pilopa commented
Requires https://github.com/scm-manager/scm-manager/pull/1877

2021-11-30 08:49 UTC, merged